name: ðŸ“š Deploy MkDocs to Vercel

on:
  push:
    branches:
      - main
    paths:
      - 'documentacion-luenser/**'              
      - '.github/workflows/deploy-docs.yml'   

jobs:
  deploy-to-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install MkDocs & plugins
        run: |
          pip install mkdocs mkdocs-material mkdocs-minify-plugin

      - name: Build MkDocs site
        working-directory: documentacion-luenser
        run: mkdocs build --clean

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        working-directory: documentacion-luenser/public
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          vercel --prod --confirm --token $VERCEL_TOKEN
